### ISSUE TITLE
API v3 /events - Timeout

### ISSUE THREAD

**Issue by muhlba91** [hella-info/onyx_api#9] opened 2023-12-12 08:54 UTC
Hi,

I created the Python client (https://github.com/muhlba91/onyx-client) and the Home Assistant integration (https://github.com/muhlba91/onyx-homeassistant-integration).

I rely on your provided `/events` endpoint for device updates. This works well as long as the connection is kept open.
In the client, I set an indefinite timeout, which should keep the connection open from the client side forever - see https://github.com/muhlba91/onyx-client/blob/main/onyx_client/helpers/url.py#L87.
Unfortunately, every ~10 minutes, the connection closes, and I need to reopen it, which is not the purpose of such an events endpoint to have to reopen it every 10 minutes.

So far, a server-side connection timeout could cause this. Could you look at this and, if true, possibly set a server timeout for this endpoint to a much higher one than 10 minutes?

**Comment by joseffilzmaier** [comment] 2023-12-12 14:34
Thank you for the report. We can reproduce the issue and are investigating the root cause, i will give you a notice here once we have an explanation/fix for this behavior.

**Comment by joseffilzmaier** [comment] 2023-12-12 15:19
We have located the issue. It can only be resolved by a firmware update for ONYX.CENTER and will be fixed with our upcoming `2.9.x` OS Version by introducing heartbeats on the `/events` endpoint.

A workaround would be to trigger any kind of traffic within the 10 Minute timeout window (e.g. creating/renaming/deleting groups, ...)

**Comment by muhlba91** [comment] 2024-09-14 07:26
@joseffilzmaier is there any update on the release of this version?

**Comment by joseffilzmaier** [comment] 2024-09-19 16:58
We are working on the upcoming `2.9.x` release of the OS and are currently targeting a release within this year. Note that this target can still change if unforeseen issues arise. Thank you for your patience!

**Comment by joseffilzmaier** [comment] 2024-11-29 09:17
@muhlba91 We are currently in the process of releasing our OS Update version `2.9.4` which fixes this issue.
There are some additions and smaller changes in the API. Please refer to https://gitlab.com/hella-info/onyx_api for further information.

**Closed as completed** 2024-11-29 10:39 UTC

**Comment by muhlba91** [comment] 2024-12-01 09:02
awesome, thank you for letting me know! so far, the problem has not occurred anymore. 🎉
